// Date: 21/06/2015 22:59:20
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package sonar.calculator.mod.client.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelFluxModule extends ModelBase
{
  //fields
    ModelRenderer Body;
    ModelRenderer Screen;
    ModelRenderer Body2;
    ModelRenderer Body3;
    ModelRenderer Body4;
    ModelRenderer Screen2;
    ModelRenderer Base;
    ModelRenderer Rib1;
    ModelRenderer Rib2;
    ModelRenderer Rib3;
    ModelRenderer Rib4;
    ModelRenderer Rib5;
    ModelRenderer Body5;
    ModelRenderer Body6;
    ModelRenderer Antenna1;
    ModelRenderer Antenna2;
    ModelRenderer Antenna3;
    ModelRenderer Antenna4;
    ModelRenderer Antenna5;
    ModelRenderer Antenna6;
  
  public ModelFluxModule()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      Body = new ModelRenderer(this, 0, 57);
      Body.addBox(0F, 0F, 0F, 10, 4, 3);
      Body.setRotationPoint(-5F, 8F, -2F);
      Body.setTextureSize(128, 64);
      Body.mirror = true;
      setRotation(Body, 0F, 0F, 0F);
      Screen = new ModelRenderer(this, 0, 51);
      Screen.addBox(0F, 0F, 0F, 12, 5, 1);
      Screen.setRotationPoint(-6F, 4F, -4F);
      Screen.setTextureSize(128, 64);
      Screen.mirror = true;
      setRotation(Screen, -0.1115358F, 0F, 0F);
      Body2 = new ModelRenderer(this, 0, 48);
      Body2.addBox(0F, 0F, 0F, 8, 1, 2);
      Body2.setRotationPoint(-4F, 7F, -1F);
      Body2.setTextureSize(128, 64);
      Body2.mirror = true;
      setRotation(Body2, 0F, 0F, 0F);
      Body3 = new ModelRenderer(this, 0, 38);
      Body3.addBox(0F, 0F, 0F, 1, 9, 1);
      Body3.setRotationPoint(-5.5F, 13F, -1F);
      Body3.setTextureSize(128, 64);
      Body3.mirror = true;
      setRotation(Body3, 0F, 0F, 0F);
      Body4 = new ModelRenderer(this, 0, 38);
      Body4.addBox(0F, 0F, 0F, 1, 9, 1);
      Body4.setRotationPoint(4.5F, 13F, -1F);
      Body4.setTextureSize(128, 64);
      Body4.mirror = true;
      setRotation(Body4, 0F, 0F, 0F);
      Screen2 = new ModelRenderer(this, 0, 42);
      Screen2.addBox(0F, 0F, 0F, 1, 5, 1);
      Screen2.setRotationPoint(0F, 7F, -4F);
      Screen2.setTextureSize(128, 64);
      Screen2.mirror = true;
      setRotation(Screen2, 1.115358F, 0F, 0F);
      Base = new ModelRenderer(this, 26, 58);
      Base.addBox(0F, 0F, 0F, 12, 2, 4);
      Base.setRotationPoint(-6F, 22F, -2.5F);
      Base.setTextureSize(128, 64);
      Base.mirror = true;
      setRotation(Base, 0F, 0F, 0F);
      Rib1 = new ModelRenderer(this, 0, 0);
      Rib1.addBox(0F, 0F, 0F, 12, 1, 4);
      Rib1.setRotationPoint(-6F, 20F, -2.5F);
      Rib1.setTextureSize(128, 64);
      Rib1.mirror = true;
      setRotation(Rib1, 0F, 0F, 0F);
      Rib2 = new ModelRenderer(this, 0, 0);
      Rib2.addBox(0F, 0F, 0F, 12, 1, 4);
      Rib2.setRotationPoint(-6F, 18F, -2.5F);
      Rib2.setTextureSize(128, 64);
      Rib2.mirror = true;
      setRotation(Rib2, 0F, 0F, 0F);
      Rib3 = new ModelRenderer(this, 0, 0);
      Rib3.addBox(0F, 0F, 0F, 12, 1, 4);
      Rib3.setRotationPoint(-6F, 16F, -2.5F);
      Rib3.setTextureSize(128, 64);
      Rib3.mirror = true;
      setRotation(Rib3, 0F, 0F, 0F);
      Rib4 = new ModelRenderer(this, 0, 0);
      Rib4.addBox(0F, 0F, 0F, 12, 1, 4);
      Rib4.setRotationPoint(-6F, 14F, -2.5F);
      Rib4.setTextureSize(128, 64);
      Rib4.mirror = true;
      setRotation(Rib4, 0F, 0F, 0F);
      Rib5 = new ModelRenderer(this, 0, 0);
      Rib5.addBox(0F, 0F, 0F, 12, 1, 4);
      Rib5.setRotationPoint(-6F, 12F, -2.5F);
      Rib5.setTextureSize(128, 64);
      Rib5.mirror = true;
      setRotation(Rib5, 0F, 0F, 0F);
      Body5 = new ModelRenderer(this, 26, 45);
      Body5.addBox(0F, 0F, 0F, 8, 12, 1);
      Body5.setRotationPoint(-4F, 11F, 1F);
      Body5.setTextureSize(128, 64);
      Body5.mirror = true;
      setRotation(Body5, 0F, 0F, 0F);
      Body6 = new ModelRenderer(this, 4, 39);
      Body6.addBox(0F, 0F, 0F, 8, 8, 1);
      Body6.setRotationPoint(-4F, 11F, -3F);
      Body6.setTextureSize(128, 64);
      Body6.mirror = true;
      setRotation(Body6, 0F, 0F, 0F);
      Antenna1 = new ModelRenderer(this, 32, 0);
      Antenna1.addBox(0F, 0F, 0F, 1, 6, 1);
      Antenna1.setRotationPoint(-8F, 6F, -1F);
      Antenna1.setTextureSize(128, 64);
      Antenna1.mirror = true;
      setRotation(Antenna1, 0F, 0F, -0.7853982F);
      Antenna2 = new ModelRenderer(this, 36, 0);
      Antenna2.addBox(0F, 0F, 0F, 5, 1, 5);
      Antenna2.setRotationPoint(-10F, 7F, -3F);
      Antenna2.setTextureSize(128, 64);
      Antenna2.mirror = true;
      setRotation(Antenna2, 0F, 0F, -0.7853982F);
      Antenna3 = new ModelRenderer(this, 36, 6);
      Antenna3.addBox(0F, 0F, 0F, 3, 1, 3);
      Antenna3.setRotationPoint(-10F, 6F, -2F);
      Antenna3.setTextureSize(128, 64);
      Antenna3.mirror = true;
      setRotation(Antenna3, 0F, 0F, -0.7853982F);
      Antenna4 = new ModelRenderer(this, 56, 0);
      Antenna4.addBox(0F, 0F, 0F, 1, 5, 3);
      Antenna4.setRotationPoint(2F, 2F, -2F);
      Antenna4.setTextureSize(128, 64);
      Antenna4.mirror = true;
      setRotation(Antenna4, 0F, 0F, 0F);
      Antenna5 = new ModelRenderer(this, 56, 0);
      Antenna5.addBox(0F, 0F, 0F, 1, 16, 1);
      Antenna5.setRotationPoint(3F, -9F, 0F);
      Antenna5.setTextureSize(128, 64);
      Antenna5.mirror = true;
      setRotation(Antenna5, 0F, 0F, 0F);
      Antenna6 = new ModelRenderer(this, 56, 0);
      Antenna6.addBox(0F, 0F, 0F, 1, 9, 1);
      Antenna6.setRotationPoint(3F, -2F, -1F);
      Antenna6.setTextureSize(128, 64);
      Antenna6.mirror = true;
      setRotation(Antenna6, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5, boolean antenna)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(entity, f, f1, f2, f3, f4, f5);
    Body.render(f5);
    Screen.render(f5);
    Body2.render(f5);
    Body3.render(f5);
    Body4.render(f5);
    Screen2.render(f5);
    Base.render(f5);
    Rib1.render(f5);
    Rib2.render(f5);
    Rib3.render(f5);
    Rib4.render(f5);
    Rib5.render(f5);
    Body5.render(f5);
    Body6.render(f5);
    Antenna1.render(f5);
    Antenna2.render(f5);
    Antenna3.render(f5);
    Antenna4.render(f5);
    if(antenna){
    Antenna5.render(f5);
    Antenna6.render(f5);
    }
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
