// Date: 12/05/2015 08:58:15
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package sonar.calculator.mod.client.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelWeatherStationDish extends ModelBase {
  //fields
    ModelRenderer Base;
    ModelRenderer Side1;
    ModelRenderer Side2;
    ModelRenderer Side3;
    ModelRenderer Side4;
    ModelRenderer Side5;
    ModelRenderer Side6;
    ModelRenderer Side7;
    ModelRenderer Side8;
    ModelRenderer Support1;
    ModelRenderer Support2;
    ModelRenderer Beam;
    ModelRenderer Middle1;
    ModelRenderer Middle2;
  
    public ModelWeatherStationDish() {
    textureWidth = 128;
    textureHeight = 64;
    
      Base = new ModelRenderer(this, 0, 36);
      Base.addBox(0F, 0F, 0F, 26, 2, 26);
      Base.setRotationPoint(-13F, 22F, -13F);
      Base.setTextureSize(128, 64);
      Base.mirror = true;
      setRotation(Base, 0F, 0F, 0F);
      Side1 = new ModelRenderer(this, 0, 0);
      Side1.addBox(0F, 0F, 0F, 28, 2, 2);
      Side1.setRotationPoint(-14F, 20F, 12F);
      Side1.setTextureSize(128, 64);
      Side1.mirror = true;
      setRotation(Side1, 0F, 0F, 0F);
      Side2 = new ModelRenderer(this, 0, 0);
      Side2.addBox(0F, 0F, 0F, 28, 2, 2);
      Side2.setRotationPoint(-14F, 20F, -14F);
      Side2.setTextureSize(128, 64);
      Side2.mirror = true;
      setRotation(Side2, 0F, 0F, 0F);
      Side3 = new ModelRenderer(this, 0, 0);
      Side3.addBox(0F, 0F, 0F, 24, 2, 2);
      Side3.setRotationPoint(12F, 20F, 12F);
      Side3.setTextureSize(128, 64);
      Side3.mirror = true;
      setRotation(Side3, 0F, 1.570796F, 0F);
      Side4 = new ModelRenderer(this, 0, 0);
      Side4.addBox(0F, 0F, 0F, 24, 2, 2);
      Side4.setRotationPoint(-14F, 20F, 12F);
      Side4.setTextureSize(128, 64);
      Side4.mirror = true;
      setRotation(Side4, 0F, 1.570796F, 0F);
      Side5 = new ModelRenderer(this, 0, 0);
      Side5.addBox(0F, 0F, 0F, 32, 2, 2);
      Side5.setRotationPoint(-16F, 18F, 13F);
      Side5.setTextureSize(128, 64);
      Side5.mirror = true;
      setRotation(Side5, 0F, 0F, 0F);
      Side6 = new ModelRenderer(this, 0, 0);
      Side6.addBox(0F, 0F, 0F, 32, 2, 2);
      Side6.setRotationPoint(-16F, 18F, -15F);
      Side6.setTextureSize(128, 64);
      Side6.mirror = true;
      setRotation(Side6, 0F, 0F, 0F);
      Side7 = new ModelRenderer(this, 0, 0);
      Side7.addBox(0F, 0F, 0F, 26, 2, 2);
      Side7.setRotationPoint(-16F, 18F, 13F);
      Side7.setTextureSize(128, 64);
      Side7.mirror = true;
      setRotation(Side7, 0F, 1.570796F, 0F);
      Side8 = new ModelRenderer(this, 0, 0);
      Side8.addBox(0F, 0F, 0F, 26, 2, 2);
      Side8.setRotationPoint(14F, 18F, 13F);
      Side8.setTextureSize(128, 64);
      Side8.mirror = true;
      setRotation(Side8, 0F, 1.570796F, 0F);
      Support1 = new ModelRenderer(this, 0, 18);
      Support1.addBox(0F, 0F, 0F, 2, 16, 2);
      Support1.setRotationPoint(-2F, 9F, -13F);
      Support1.setTextureSize(128, 64);
      Support1.mirror = true;
      setRotation(Support1, 0F, 0F, -0.5235988F);
      Support2 = new ModelRenderer(this, 0, 18);
      Support2.addBox(0F, 0F, 0F, 2, 16, 2);
      Support2.setRotationPoint(0F, 8F, -13F);
      Support2.setTextureSize(128, 64);
      Support2.mirror = true;
      setRotation(Support2, 0F, 0F, 0.5235988F);
      Beam = new ModelRenderer(this, 0, 10);
      Beam.addBox(0F, 0F, 0F, 4, 4, 4);
      Beam.setRotationPoint(-2F, 6F, -14F);
      Beam.setTextureSize(128, 64);
      Beam.mirror = true;
      setRotation(Beam, 0F, 0F, 0F);
      Middle1 = new ModelRenderer(this, 24, 27);
      Middle1.addBox(0F, 0F, 0F, 8, 1, 8);
      Middle1.setRotationPoint(-4F, 21F, -4F);
      Middle1.setTextureSize(128, 64);
      Middle1.mirror = true;
      setRotation(Middle1, 0F, 0F, 0F);
      Middle2 = new ModelRenderer(this, 8, 30);
      Middle2.addBox(0F, 0F, 0F, 4, 2, 4);
      Middle2.setRotationPoint(-2F, 19F, -2F);
      Middle2.setTextureSize(128, 64);
      Middle2.mirror = true;
      setRotation(Middle2, 0F, 0F, 0F);
  }
  
    @Override
    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(entity, f, f1, f2, f3, f4, f5);
    Base.render(f5);
    Side1.render(f5);
    Side2.render(f5);
    Side3.render(f5);
    Side4.render(f5);
    Side5.render(f5);
    Side6.render(f5);
    Side7.render(f5);
    Side8.render(f5);
    Support1.render(f5);
    Support2.render(f5);
    Beam.render(f5);
    Middle1.render(f5);
    Middle2.render(f5);
  }
  
    private void setRotation(ModelRenderer model, float x, float y, float z) {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
    public void setRotationAngles(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }
}
