// Date: 11/01/2015 18:00:25
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package sonar.calculator.mod.client.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelLantern extends ModelBase
{
  //fields
    ModelRenderer Bottom;
    ModelRenderer Bottom2;
    ModelRenderer Bottom3;
    ModelRenderer Lamp;
    ModelRenderer Top3;
    ModelRenderer Top2;
    ModelRenderer Top;
  
  public ModelLantern()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Bottom = new ModelRenderer(this, 0, 27);
      Bottom.addBox(0F, 0F, 0F, 4, 1, 4);
      Bottom.setRotationPoint(-2F, 23F, -2F);
      Bottom.setTextureSize(64, 32);
      Bottom.mirror = true;
      setRotation(Bottom, 0F, 0F, 0F);
      Bottom2 = new ModelRenderer(this, 8, 14);
      Bottom2.addBox(0F, 0F, 0F, 2, 1, 2);
      Bottom2.setRotationPoint(-1F, 22F, -1F);
      Bottom2.setTextureSize(64, 32);
      Bottom2.mirror = true;
      setRotation(Bottom2, 0F, 0F, 0F);
      Bottom3 = new ModelRenderer(this, 0, 10);
      Bottom3.addBox(0F, 0F, 0F, 6, 1, 6);
      Bottom3.setRotationPoint(-3F, 21F, -3F);
      Bottom3.setTextureSize(64, 32);
      Bottom3.mirror = true;
      setRotation(Bottom3, 0F, 0F, 0F);
      Lamp = new ModelRenderer(this, 0, 0);
      Lamp.addBox(0F, 0F, 0F, 4, 6, 4);
      Lamp.setRotationPoint(-2F, 15F, -2F);
      Lamp.setTextureSize(64, 32);
      Lamp.mirror = true;
      setRotation(Lamp, 0F, 0F, 0F);
      Top3 = new ModelRenderer(this, 24, 10);
      Top3.addBox(0F, 0F, 0F, 6, 1, 6);
      Top3.setRotationPoint(-3F, 14F, -3F);
      Top3.setTextureSize(64, 32);
      Top3.mirror = true;
      setRotation(Top3, 0F, 0F, 0F);
      Top2 = new ModelRenderer(this, 0, 27);
      Top2.addBox(0F, 0F, 0F, 4, 1, 4);
      Top2.setRotationPoint(-2F, 13F, -2F);
      Top2.setTextureSize(64, 32);
      Top2.mirror = true;
      setRotation(Top2, 0F, 0F, 0F);
      Top = new ModelRenderer(this, 0, 17);
      Top.addBox(0F, 0F, 0F, 2, 1, 2);
      Top.setRotationPoint(-1F, 12F, -1F);
      Top.setTextureSize(64, 32);
      Top.mirror = true;
      setRotation(Top, 0F, 0F, 0F);
  }
  
  @Override
public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Bottom.render(f5);
    Bottom2.render(f5);
    Bottom3.render(f5);
    Lamp.render(f5);
    Top3.render(f5);
    Top2.render(f5);
    Top.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  @Override
public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
