// Date: 03/04/2016 16:42:05
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelNew extends ModelBase
{
  //fields
    ModelRenderer Arm1;
    ModelRenderer Arm2;
    ModelRenderer Arm3;
    ModelRenderer Arm4;
    ModelRenderer Base;
  
  public ModelNew()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Arm1 = new ModelRenderer(this, 0, 24);
      Arm1.addBox(-1F, -0.5F, -6F, 1, 1, 7);
      Arm1.setRotationPoint(-1F, 22F, 0F);
      Arm1.setTextureSize(64, 32);
      Arm1.mirror = true;
      setRotation(Arm1, -0.7853982F, 0F, 0F);
      Arm2 = new ModelRenderer(this, 0, 24);
      Arm2.addBox(0F, -0.5F, -6F, 1, 1, 7);
      Arm2.setRotationPoint(1F, 22F, 0F);
      Arm2.setTextureSize(64, 32);
      Arm2.mirror = true;
      setRotation(Arm2, -0.7853982F, 0F, 0F);
      Arm3 = new ModelRenderer(this, 16, 24);
      Arm3.addBox(-1F, -0.5F, -6F, 2, 1, 7);
      Arm3.setRotationPoint(0F, 18F, -4F);
      Arm3.setTextureSize(64, 32);
      Arm3.mirror = true;
      setRotation(Arm3, 0F, 0F, 0F);
      Arm4 = new ModelRenderer(this, 0, 21);
      Arm4.addBox(-1F, 0.5F, -5F, 2, 2, 1);
      Arm4.setRotationPoint(0F, 18F, -4F);
      Arm4.setTextureSize(64, 32);
      Arm4.mirror = true;
      setRotation(Arm4, 0F, 0F, 0F);
      Base = new ModelRenderer(this, 6, 20);
      Base.addBox(0F, 0F, 0F, 2, 2, 2);
      Base.setRotationPoint(-1F, 22F, -0.5F);
      Base.setTextureSize(64, 32);
      Base.mirror = true;
      setRotation(Base, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Arm1.render(f5);
    Arm2.render(f5);
    Arm3.render(f5);
    Arm4.render(f5);
    Base.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
